services:

  mysql:
    image: mysql:8

    container_name: mysql-container

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datalake

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: datalake-backend

    container_name: datalake-backend-container

    ports:
      - "3002:3000"

    depends_on:
      - mysql

volumes:
  mysql-data: